artifacts_root_dir: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Rutvik46/dataset-repo/raw/refs/heads/main/heart.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion/heart.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/heart.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_names: 
    model1: Support_Vector_Machine.joblib
    model2: K_Nearest_Neighbours.joblib
    model3: AdaBoost.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_paths: 
    - artifacts/model_trainer/Support_Vector_Machine.joblib
    - artifacts/model_trainer/K_Nearest_Neighbours.joblib
    - artifacts/model_trainer/AdaBoost.joblib

  test_data_path: artifacts/data_transformation/test.csv
  metrics_file_paths: 
    - artifacts/model_evaluation/Support_Vector_Machine.json
    - artifacts/model_evaluation/K_Nearest_Neighbours.json
    - artifacts/model_evaluation/AdaBoost.json